"""enforce eager loading at the enforce eager loading at the model leve model level

Revision ID: 18fd48c89b58
Revises: cecdece4629f
Create Date: 2025-06-04 20:50:49.691823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18fd48c89b58'
down_revision: Union[str, None] = 'cecdece4629f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
