"""user password_hash

Revision ID: 977e7de255f4
Revises: ae39f35daf14
Create Date: 2025-06-08 10:46:44.866961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '977e7de255f4'
down_revision: Union[str, None] = 'ae39f35daf14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('password_hash', sa.String(), nullable=False))
    op.drop_column('auth_users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('auth_users', 'password_hash')
    # ### end Alembic commands ###
